import type { MeditationPlan } from '@/data/meditationPlans';

const shortPrompts = (items: string[]): string[] => items;

export const foundationParablePlans: MeditationPlan[] = [
  {
    id: 'sower',
    title: 'Sower',
    parable: 'Parable of the Sower',
    scripture: 'Luke 8:4-8',
    overview: 'Seed meets soil.',
    breathInvitation: 'Slow breath. Receive.',
    reflectionPrompts: shortPrompts(['Think about your distractions.', 'How will you create more time for God?', 'Untangle your life, do not let emergencies teach you.', 'Simplify your life.']),
    focusOptions: ['Silence phone', 'Journal one line', 'Encourage someone'],
    challengePrompt: 'Choose one small obedience today.',
    closingReminder: 'Is the world choking you?',
    openReflection: 'Where did you notice thorns (worry/tasks)?',
    guidanceTips: ['Schedule 5 quiet mins.', 'Put verse on lock screen.'],
    stageNote: 'Begin again.',
  },
  {
    id: 'mustard-seed',
    title: 'Mustard Seed',
    parable: 'Parable of the Mustard Seed',
    scripture: 'Matthew 13:31-32',
    overview: 'Small shelters.',
    breathInvitation: 'Inhale seed. Exhale trust.',
    reflectionPrompts: shortPrompts(['Name your small start.', 'Plan a 10‑minute step.', 'Tell a friend for accountability.', 'Thank God for unseen growth.']),
    focusOptions: ['Start small', 'Show up daily', 'Celebrate tiny wins'],
    challengePrompt: 'Do one 10‑minute action.',
    closingReminder: 'Small + faithful.',
    openReflection: 'What “seed” is God asking you to tend today?',
    guidanceTips: ['Block calendar 10 min.', 'Ignore comparison.'],
    stageNote: 'Gentle growth.',
  },
  {
    id: 'good-samaritan',
    title: 'Good Samaritan',
    parable: 'Parable of the Good Samaritan',
    scripture: 'Luke 10:25-37',
    overview: 'Mercy stops.',
    breathInvitation: 'Inhale mercy. Exhale hurry.',
    reflectionPrompts: shortPrompts(['Notice one person you’d normally pass.', 'Offer help (text, ride, meal).', 'Ask “How can I pray for you?”', 'Schedule follow‑up.']),
    focusOptions: ['See need', 'Stop hurry', 'Serve simply'],
    challengePrompt: 'Interrupt your schedule for love once.',
    closingReminder: 'Mercy moves.',
    openReflection: 'Who is on your path today?',
    guidanceTips: ['Carry a $5 gift card.', 'Add a “care” reminder.'],
    stageNote: 'Learning compassion.',
  },
  {
    id: 'lost-sheep',
    title: 'Lost Sheep',
    parable: 'Parable of the Lost Sheep',
    scripture: 'Luke 15:1-7',
    overview: 'Found and carried.',
    breathInvitation: 'Inhale rest. Exhale trust.',
    reflectionPrompts: shortPrompts(['Name where you feel lost.', 'Ask for help out loud.', 'Receive grace—no earning.', 'Celebrate a small return.']),
    focusOptions: ['Ask help', 'Receive', 'Celebrate'],
    challengePrompt: 'Tell someone you need help today.',
    closingReminder: 'Let yourself be carried.',
    openReflection: 'Who can you celebrate grace with tonight?',
    guidanceTips: ['Text a trusted friend.', 'Plan a gratitude walk.'],
    stageNote: 'Belonging.',
  },
  {
    id: 'wise-builder',
    title: 'Wise Builder',
    parable: 'Parable of the Wise and Foolish Builders',
    scripture: 'Matthew 7:24-27',
    overview: 'Rock holds.',
    breathInvitation: 'Breathe strength. Release tension.',
    reflectionPrompts: shortPrompts(['Are your habits rooted in Christ.', 'How can you purify your daily routine?', 'Decide one boundary (sleep, screen).', 'Do it today.']),
    focusOptions: ['Anchor', 'Boundary', 'Repeat'],
    challengePrompt: 'Do something to purify your daily routine.',
    closingReminder: 'Build before storms.',
    openReflection: 'What daily rhythm needs a rebuild?',
    guidanceTips: ['Post verse at workspace.', 'Turn off one notification.'],
    stageNote: 'Steady footing.',
  },
];

export const growthParablePlans: MeditationPlan[] = [
  {
    id: 'prayer-persistence',
    title: 'Persistent Friend',
    parable: 'Parable of the Friend at Midnight',
    scripture: 'Luke 11:5-10',
    overview: 'Night knock.',
    breathInvitation: 'Breathe courage. Breathe patience.',
    reflectionPrompts: shortPrompts(['Write a 1‑sentence request to God.', 'Set a daily reminder to pray.', 'Ask a friend to pray with you for something you want.', 'God hears us, persistence obtains more merit.']),
    focusOptions: ['Ask', 'Remind', 'Agree'],
    challengePrompt: 'Pray it at two set times.',
    closingReminder: 'Ask. Seek. Knock.',
    openReflection: 'What door needs another knock?',
    guidanceTips: ['Put request on fridge.', 'Use alarm title as prayer.'],
    stageNote: 'Enduring trust.',
  },
  {
    id: 'talents',
    title: 'Talents',
    parable: 'Parable of the Talents',
    scripture: 'Matthew 25:14-30',
    overview: 'Gifts entrusted.',
    breathInvitation: 'Inhale courage. Exhale comparison.',
    reflectionPrompts: shortPrompts(['List one gift you’re burying.', 'Offer it for service once this week.', 'Email someone to help.', 'Do one small risk today.']),
    focusOptions: ['Name', 'Offer', 'Act'],
    challengePrompt: 'Share your gift with one person.',
    closingReminder: 'Faithful over little.',
    openReflection: 'Who needs what you have?',
    guidanceTips: ['Block 30 min to practice.', 'Ignore perfection.'],
    stageNote: 'Courageous stewardship.',
  },
  {
    id: 'unforgiving-servant',
    title: 'Merciful Servant',
    parable: 'Parable of the Unforgiving Servant',
    scripture: 'Matthew 18:21-35',
    overview: 'Mercy released.',
    breathInvitation: 'Inhale grace. Exhale mercy.',
    reflectionPrompts: shortPrompts(['Name the debt you hold.', 'Release them to God in prayer.', 'Choose one blessing to speak.', 'Set a wise boundary if needed.']),
    focusOptions: ['Release', 'Bless', 'Boundary'],
    challengePrompt: 'Pray blessing over them by name.',
    closingReminder: 'Mercy received, mercy given.',
    openReflection: 'What protects your heart while forgiving?',
    guidanceTips: ['Write a release note.', 'Talk to a counselor/friend.'],
    stageNote: 'Stretching compassion.',
  },
  {
    id: 'ten-virgins',
    title: 'Ready Lamps',
    parable: 'Parable of the Ten Virgins',
    scripture: 'Matthew 25:1-13',
    overview: 'Oil kept.',
    breathInvitation: 'Inhale expectancy. Exhale preparation.',
    reflectionPrompts: shortPrompts(['Check your “oil” (sleep, Word, community).', 'Schedule replenishing time.', 'Prepare one thing for tomorrow.', 'Say no to one drain.']),
    focusOptions: ['Rest', 'Word', 'Community'],
    challengePrompt: 'Plan one refill today.',
    closingReminder: 'Stay ready, not rushed.',
    openReflection: 'What drains your oil fastest?',
    guidanceTips: ['Prep tomorrow bag.', 'Set bedtime alarm.'],
    stageNote: 'Resilient waiting.',
  },
  {
    id: 'vineyard-workers',
    title: 'Vineyard Grace',
    parable: 'Parable of the Workers in the Vineyard',
    scripture: 'Matthew 20:1-16',
    overview: 'Grace levels.',
    breathInvitation: 'Breathe gratitude. Release envy.',
    reflectionPrompts: shortPrompts(['Identify an envy trigger.', 'Thank God for your portion; celebrate others.', 'Envy steals from your future.']),
    focusOptions: ['Thank', 'Celebrate', 'Cooperate'],
    challengePrompt: 'Send one “congrats” message.',
    closingReminder: 'Grace is enough.',
    openReflection: 'Where did jealousy show up today?',
    guidanceTips: ['Do a gratitude list.', 'Mute envy‑feeding accounts.'],
    stageNote: 'Shared celebration.',
  },
];

export const deepParablePlans: MeditationPlan[] = [
  {
    id: 'treasure-field',
    title: 'Hidden Treasure',
    parable: 'Parable of the Hidden Treasure',
    scripture: 'Matthew 13:44',
    overview: 'Joy discovered.',
    breathInvitation: 'Inhale wonder. Exhale surrender.',
    reflectionPrompts: shortPrompts(['Name the treasure you’ve found in Christ.', 'Choose one costly “yes.”', 'Release one lesser thing.', 'Plan a joyful act of witness.']),
    focusOptions: ['Yes', 'Release', 'Witness'],
    challengePrompt: 'Trade one distraction for devotion today.',
    closingReminder: 'Joy fuels sacrifice.',
    openReflection: 'What will you gladly sell for the treasure?',
    guidanceTips: ['Uninstall one app today.', 'Share your story with a friend.'],
    stageNote: 'Guarded wonder.',
  },
  {
    id: 'true-vine',
    title: 'True Vine',
    parable: 'Metaphor of the Vine and Branches',
    scripture: 'John 15:1-11',
    overview: 'Life flows.',
    breathInvitation: 'Inhale abide. Exhale release.',
    reflectionPrompts: shortPrompts(['Schedule 10 minutes to abide.', 'Identify pruning you’re resisting.', 'Choose love in a hard reply.', 'Name today’s fruit.']),
    focusOptions: ['Abide', 'Prune', 'Love'],
    challengePrompt: 'Two 5‑minute abides today.',
    closingReminder: 'Remain in love.',
    openReflection: 'Where do you need pruning?',
    guidanceTips: ['Set silence timer.', 'Turn a commute into prayer.'],
    stageNote: 'Mature abiding.',
  },
  {
    id: 'prodigal-father',
    title: 'Restoring Father',
    parable: 'Parable of the Prodigal Son',
    scripture: 'Luke 15:11-32',
    overview: 'Arms open.',
    breathInvitation: 'Inhale welcome. Exhale pride.',
    reflectionPrompts: shortPrompts(['Own one area to repent.', 'Receive the Father’s embrace.', 'Initiate reconciliation (text/call).', 'Plan a celebration meal.']),
    focusOptions: ['Repent', 'Receive', 'Reconcile'],
    challengePrompt: 'Make the first move in peace.',
    closingReminder: 'The Father runs to you.',
    openReflection: 'Who needs your welcome today?',
    guidanceTips: ['Write the apology draft.', 'Set a date to meet.'],
    stageNote: 'Expansive mercy.',
  },
  {
    id: 'pearl-merchant',
    title: 'Pearl Merchant',
    parable: 'Parable of the Pearl of Great Price',
    scripture: 'Matthew 13:45-46',
    overview: 'Worth beyond all.',
    breathInvitation: 'Breathe surrender. Hold peace.',
    reflectionPrompts: shortPrompts(['Name your “pearl.”', 'Drop one lesser attachment.', 'Redirect money/time to kingdom work.', 'Commit publicly to the choice.']),
    focusOptions: ['Value', 'Trade', 'Commit'],
    challengePrompt: 'Make one costly, faithful trade today.',
    closingReminder: 'Choose the better portion.',
    openReflection: 'What are you willing to lay down?',
    guidanceTips: ['Budget first‑fruit giving.', 'Tell a friend your trade.'],
    stageNote: 'Singular focus.',
  },
];
