import type { MeditationPlan } from '@/data/meditationPlans';

const shortPrompts = (items: string[]): string[] => items;

export const foundationParablePlans: MeditationPlan[] = [
  {
    id: 'sower',
    title: 'Sower',
    parable: 'Parable of the Sower',
    scripture: 'Luke 8:4-8',
    overview: 'Seed meets soil.',
    breathInvitation: 'Slow breath. Receive.',
    reflectionPrompts: shortPrompts(['Soil?', 'Receive.', 'Guard.', 'Share.']),
    focusOptions: ['Listen', 'Tend', 'Hope'],
    challengePrompt: 'Let the seed guide today.',
    closingReminder: 'Stay good soil.',
    openReflection: 'Where is the seed landing?',
    guidanceTips: ['Whisper the verse.', 'Keep posture soft.'],
    stageNote: 'Begin again.',
  },
  {
    id: 'mustard-seed',
    title: 'Mustard Seed',
    parable: 'Parable of the Mustard Seed',
    scripture: 'Matthew 13:31-32',
    overview: 'Small shelters.',
    breathInvitation: 'Inhale small. Exhale trust.',
    reflectionPrompts: shortPrompts(['Notice.', 'Water.', 'Wait.', 'Celebrate.']),
    focusOptions: ['Protect', 'Rest', 'Bless'],
    challengePrompt: 'Let the seed set your pace.',
    closingReminder: 'Grow steady.',
    openReflection: 'What small grace is rising?',
    guidanceTips: ['Name one next step.', 'Thank God for the unseen.'],
    stageNote: 'Gentle growth.',
  },
  {
    id: 'good-samaritan',
    title: 'Good Samaritan',
    parable: 'Parable of the Good Samaritan',
    scripture: 'Luke 10:25-37',
    overview: 'Mercy stops.',
    breathInvitation: 'Inhale mercy. Exhale hurry.',
    reflectionPrompts: shortPrompts(['Who waits?', 'Receive help.', 'Offer care.', 'Move slow.']),
    focusOptions: ['See', 'Kneel', 'Serve'],
    challengePrompt: 'Let mercy answer your tension.',
    closingReminder: 'Walk with open eyes.',
    openReflection: 'Who is on your roadside?',
    guidanceTips: ['Pause before reacting.', 'Choose one small kindness.'],
    stageNote: 'Learning compassion.',
  },
  {
    id: 'lost-sheep',
    title: 'Lost Sheep',
    parable: 'Parable of the Lost Sheep',
    scripture: 'Luke 15:1-7',
    overview: 'Found and carried.',
    breathInvitation: 'Inhale rest. Exhale trust.',
    reflectionPrompts: shortPrompts(['Where lost?', 'Let Him lift.', 'Feel joy.', 'Share grace.']),
    focusOptions: ['Rest', 'Rejoice', 'Remember'],
    challengePrompt: 'Let being found reshape today.',
    closingReminder: 'Return carried.',
    openReflection: 'What celebration is needed?',
    guidanceTips: ['Note gratitude.', 'Repeat “I am held.”'],
    stageNote: 'Belonging.',
  },
  {
    id: 'wise-builder',
    title: 'Wise Builder',
    parable: 'Parable of the Wise and Foolish Builders',
    scripture: 'Matthew 7:24-27',
    overview: 'Rock holds.',
    breathInvitation: 'Breathe strength. Release tension.',
    reflectionPrompts: shortPrompts(['Check base.', 'Anchor rhythm.', 'Plan obedience.', 'Stand firm.']),
    focusOptions: ['Anchor', 'Obey', 'Hold'],
    challengePrompt: 'Let the rock guide your response.',
    closingReminder: 'Step steady.',
    openReflection: 'Where do you rebuild?',
    guidanceTips: ['Repeat a grounding verse.', 'Share your plan.'],
    stageNote: 'Steady footing.',
  },
];

export const growthParablePlans: MeditationPlan[] = [
  {
    id: 'prayer-persistence',
    title: 'Persistent Friend',
    parable: 'Parable of the Friend at Midnight',
    scripture: 'Luke 11:5-10',
    overview: 'Night knock.',
    breathInvitation: 'Breathe courage. Breathe patience.',
    reflectionPrompts: shortPrompts(['Ask again.', 'Trust.', 'Wait soft.', 'Stay open.']),
    focusOptions: ['Knock', 'Listen', 'Rest'],
    challengePrompt: 'Let persistence shape your plea.',
    closingReminder: 'Keep the door in view.',
    openReflection: 'What request stays?',
    guidanceTips: ['Set one gentle reminder.', 'Release striving.'],
    stageNote: 'Enduring trust.',
  },
  {
    id: 'talents',
    title: 'Talents',
    parable: 'Parable of the Talents',
    scripture: 'Matthew 25:14-30',
    overview: 'Gifts entrusted.',
    breathInvitation: 'Inhale courage. Exhale comparison.',
    reflectionPrompts: shortPrompts(['Name gift.', 'Risk small.', 'Release fear.', 'Celebrate.']),
    focusOptions: ['Invest', 'Learn', 'Share'],
    challengePrompt: 'Let trust guide the investment.',
    closingReminder: 'Return with joy.',
    openReflection: 'Which gift wakes today?',
    guidanceTips: ['Break the step smaller.', 'Invite support.'],
    stageNote: 'Courageous stewardship.',
  },
  {
    id: 'unforgiving-servant',
    title: 'Merciful Servant',
    parable: 'Parable of the Unforgiving Servant',
    scripture: 'Matthew 18:21-35',
    overview: 'Mercy released.',
    breathInvitation: 'Inhale grace. Exhale mercy.',
    reflectionPrompts: shortPrompts(['Feel debt.', 'Receive release.', 'Offer mercy.', 'Set boundary.']),
    focusOptions: ['Forgive', 'Bless', 'Protect'],
    challengePrompt: 'Let mercy soften your stance.',
    closingReminder: 'Walk lighter.',
    openReflection: 'Who needs mercy today?',
    guidanceTips: ['Pray blessing.', 'Journal the release.'],
    stageNote: 'Stretching compassion.',
  },
  {
    id: 'ten-virgins',
    title: 'Ready Lamps',
    parable: 'Parable of the Ten Virgins',
    scripture: 'Matthew 25:1-13',
    overview: 'Oil kept.',
    breathInvitation: 'Inhale expectancy. Exhale preparation.',
    reflectionPrompts: shortPrompts(['Stay awake.', 'Tend oil.', 'Guard focus.', 'Welcome joy.']),
    focusOptions: ['Watch', 'Prepare', 'Worship'],
    challengePrompt: 'Let readiness meet your task.',
    closingReminder: 'Keep your lamp lit.',
    openReflection: 'Where is oil thin?',
    guidanceTips: ['Name renewing rhythms.', 'Rest when tired.'],
    stageNote: 'Resilient waiting.',
  },
  {
    id: 'vineyard-workers',
    title: 'Vineyard Grace',
    parable: 'Parable of the Workers in the Vineyard',
    scripture: 'Matthew 20:1-16',
    overview: 'Grace levels.',
    breathInvitation: 'Breathe gratitude. Release envy.',
    reflectionPrompts: shortPrompts(['Notice grace.', 'Bless others.', 'Receive portion.', 'Choose joy.']),
    focusOptions: ['Gratitude', 'Celebrate', 'Cooperate'],
    challengePrompt: 'Let grace steady your work.',
    closingReminder: 'Go thankful.',
    openReflection: 'Where do you compare?',
    guidanceTips: ['Replace envy with thanks.', 'Cheer another win.'],
    stageNote: 'Shared celebration.',
  },
];

export const deepParablePlans: MeditationPlan[] = [
  {
    id: 'treasure-field',
    title: 'Hidden Treasure',
    parable: 'Parable of the Hidden Treasure',
    scripture: 'Matthew 13:44',
    overview: 'Joy discovered.',
    breathInvitation: 'Inhale wonder. Exhale surrender.',
    reflectionPrompts: shortPrompts(['Name treasure.', 'Release lesser.', 'Guard joy.', 'Share hope.']),
    focusOptions: ['Treasure', 'Wonder', 'Praise'],
    challengePrompt: 'Let worth reorder choices.',
    closingReminder: 'Carry the joy.',
    openReflection: 'What treasure burns bright?',
    guidanceTips: ['Record the gift.', 'Tell the story.'],
    stageNote: 'Guarded wonder.',
  },
  {
    id: 'true-vine',
    title: 'True Vine',
    parable: 'Metaphor of the Vine and Branches',
    scripture: 'John 15:1-11',
    overview: 'Life flows.',
    breathInvitation: 'Inhale abide. Exhale release.',
    reflectionPrompts: shortPrompts(['Remain.', 'Notice pruning.', 'Bear fruit.', 'Stay joy.']),
    focusOptions: ['Abide', 'Trust', 'Fruit'],
    challengePrompt: 'Let abiding answer strain.',
    closingReminder: 'Stay in the Vine.',
    openReflection: 'Where do you feel the flow?',
    guidanceTips: ['Schedule silence.', 'Name the fruit.'],
    stageNote: 'Mature abiding.',
  },
  {
    id: 'prodigal-father',
    title: 'Restoring Father',
    parable: 'Parable of the Prodigal Son',
    scripture: 'Luke 15:11-32',
    overview: 'Arms open.',
    breathInvitation: 'Inhale welcome. Exhale pride.',
    reflectionPrompts: shortPrompts(['Which son?', 'Receive embrace.', 'Extend grace.', 'Celebrate home.']),
    focusOptions: ['Return', 'Embrace', 'Celebrate'],
    challengePrompt: 'Let welcome heal tension.',
    closingReminder: 'Live the embrace.',
    openReflection: 'Where is the feast waiting?',
    guidanceTips: ['Name who to invite.', 'Practice mercy now.'],
    stageNote: 'Expansive mercy.',
  },
  {
    id: 'pearl-merchant',
    title: 'Pearl Merchant',
    parable: 'Parable of the Pearl of Great Price',
    scripture: 'Matthew 13:45-46',
    overview: 'Worth beyond all.',
    breathInvitation: 'Breathe surrender. Hold peace.',
    reflectionPrompts: shortPrompts(['Value?', 'Release.', 'Choose.', 'Commit.']),
    focusOptions: ['Value', 'Trade', 'Trust'],
    challengePrompt: 'Let the pearl set direction.',
    closingReminder: 'Keep the pearl near.',
    openReflection: 'What do you trade today?',
    guidanceTips: ['Name attachments.', 'Thank Him for the pearl.'],
    stageNote: 'Singular focus.',
  },
];
