[req]
prompt = no
encrypt_key = no
default_bits = 2048
default_md = sha256
distinguished_name = dn

[dn]
C = US
ST = Delaware
L = Dover
O = El-Biblio
OU = Mobile
CN = ElBiblio Distribution
emailAddress = info@elbiblio.com
