import { Theme } from '@/theme';
import { Virtue } from '@/types';
import { StyleSheet, Platform } from 'react-native';

export const createStyles = (theme: Theme, currentVirtue: Virtue | undefined) => StyleSheet.create({
  container: { flex: 1, backgroundColor: theme?.colors.background },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: theme?.spacing.md,
    paddingVertical: theme?.spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: theme?.colors.border,
  },
  headerTitle: { ...theme?.typography.heading.medium, color: theme?.colors.text.primary },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollContainer: { flex: 1 },
  setupContainer: { padding: theme?.spacing.md },
  guideCard: {
    padding: theme?.spacing.md,
    borderRadius: theme?.borderRadius.lg,
    backgroundColor: theme?.colors.surface,
    borderWidth: 1,
    borderColor: theme?.colors.border,
    marginBottom: theme?.spacing.lg,
    gap: theme?.spacing.sm,
  },
  guideTitle: {
    ...theme?.typography.heading.small,
    color: theme?.colors.text.primary,
    fontWeight: '700',
  },
  guideImagery: {
    ...theme?.typography.body.sans,
    color: theme?.colors.text.secondary,
    lineHeight: 22,
  },
  guideScripture: {
    ...theme?.typography.caption.secondary,
    color: theme?.colors.text.primary,
    fontStyle: 'italic',
  },
  guideFocus: {
    ...theme?.typography.body.sans,
    color: theme?.colors.text.primary,
    fontWeight: '600',
  },
  guideStageNote: {
    ...theme?.typography.caption.secondary,
    color: theme?.colors.text.secondary,
    fontStyle: 'italic',
  },
  guideReflection: {
    ...theme?.typography.body.sans,
    color: theme?.colors.text.primary,
    marginTop: theme?.spacing.xs,
  },
  guideTipsContainer: {
    marginTop: theme?.spacing.sm,
    gap: theme?.spacing.xs,
  },
  guideTipText: {
    ...theme?.typography.caption.secondary,
    color: theme?.colors.text.secondary,
  },
  sectionTitle: {
    ...theme?.typography.caption.secondary,
    color: theme?.colors.text.secondary,
    marginTop: theme?.spacing.lg,
    marginBottom: theme?.spacing.sm,
    fontWeight: '600',
  },
  virtuesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: theme?.spacing.sm,
  },
  virtueButton: {
    width: '48%',
    paddingVertical: theme?.spacing.md,
    paddingHorizontal: theme?.spacing.sm,
    borderRadius: theme?.borderRadius.md,
    borderWidth: 1.5,
    borderColor: theme?.colors.border,
    alignItems: 'center',
    backgroundColor: theme?.colors.surface,
    marginBottom: theme?.spacing.sm,
  },
  selectedVirtueButton: { borderWidth: 2, backgroundColor: theme?.colors.background },
  virtueIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: theme?.spacing.sm,
  },
  virtueText: {
    ...theme?.typography.body.sans,
    fontWeight: '600',
    color: theme?.colors.text.primary,
  },
  timeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    marginRight: -theme?.spacing.sm,
  },
  timeButton: {
    width: '31%', // 3 per row
    paddingVertical: theme?.spacing.md,
    borderRadius: theme?.borderRadius.md,
    borderWidth: 1.5,
    borderColor: theme?.colors.border,
    alignItems: 'center',
    backgroundColor: theme?.colors.surface,
    marginRight: theme?.spacing.sm,
    marginBottom: theme?.spacing.sm,
  },
  selectedTimeButton: { borderWidth: 2, backgroundColor: theme?.colors.background },
  timeButtonContent: { flexDirection: 'row', alignItems: 'center' },
  timeText: { ...theme?.typography.body.sans, fontWeight: '600', color: theme?.colors.text.primary, marginLeft: 6 },
  customTimeButton: {
    paddingVertical: theme?.spacing.md,
    paddingHorizontal: theme?.spacing.md,
    borderRadius: theme?.borderRadius.md,
    borderWidth: 1.5,
    borderColor: theme?.colors.border,
    backgroundColor: theme?.colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: theme?.spacing.sm,
  },
  customTimeText: {
    ...theme?.typography.body.sans,
    color: theme?.colors.text.secondary,
    fontWeight: '600',
  },
  soundContainer: { flexDirection: 'row', justifyContent: 'space-between' },
  soundButton: {
    flex: 1,
    paddingVertical: theme?.spacing.md,
    borderRadius: theme?.borderRadius.md,
    borderWidth: 1.5,
    borderColor: theme?.colors.border,
    alignItems: 'center',
    backgroundColor: theme?.colors.surface,
    marginHorizontal: theme?.spacing.xs,
  },
  selectedSoundButton: { borderWidth: 2, backgroundColor: theme?.colors.background },
  soundButtonContent: { flexDirection: 'row', alignItems: 'center', gap: theme?.spacing.sm },
  soundTextGroup: { flex: 1 },
  soundText: { ...theme?.typography.body.sans, fontWeight: '600', color: theme?.colors.text.primary },
  soundDescription: {
    ...theme?.typography.caption.secondary,
    color: theme?.colors.text.secondary,
    marginTop: 2,
  },
  paceContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: theme?.spacing.sm,
    marginTop: theme?.spacing.sm,
    marginBottom: theme?.spacing.sm,
  },
  paceButton: {
    flex: 1,
    paddingVertical: theme?.spacing.md,
    paddingHorizontal: theme?.spacing.md,
    borderRadius: theme?.borderRadius.md,
    borderWidth: 1.5,
    borderColor: theme?.colors.border,
    alignItems: 'center',
    backgroundColor: theme?.colors.surface,
  },
  paceButtonActive: { borderWidth: 2 },
  paceButtonText: {
    ...theme?.typography.body.sans,
    fontWeight: '600',
    color: theme?.colors.text.primary,
  },
  paceDescription: {
    ...theme?.typography.caption.secondary,
    color: theme?.colors.text.secondary,
    marginTop: 4,
    textAlign: 'center',
  },
  challengeContainer: { gap: theme?.spacing.sm },
  challengeButton: {
    padding: theme?.spacing.md,
    borderRadius: theme?.borderRadius.md,
    borderWidth: 1.5,
    borderColor: theme?.colors.border,
    backgroundColor: theme?.colors.surface,
    overflow: 'hidden',
  },
  selectedChallengeButton: { borderWidth: 2 },
  challengeGradient: { borderRadius: theme?.borderRadius.md - 1 },
  challengeTitle: {
    ...theme?.typography.body.sans,
    fontWeight: '600',
    color: theme?.colors.text.primary,
    marginBottom: 4,
  },
  challengeDescription: {
    ...theme?.typography.caption.secondary,
    color: theme?.colors.text.secondary,
  },
  checkmarkIcon: {
    position: 'absolute',
    top: theme?.spacing.sm,
    right: theme?.spacing.sm,
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  startButton: {
    marginVertical: theme?.spacing.xl,
    paddingVertical: theme?.spacing.md,
    paddingHorizontal: theme?.spacing.xl,
    borderRadius: theme?.borderRadius.lg,
    alignItems: 'center',
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.2, shadowRadius: 8 },
      android: { elevation: 6 },
    }),
  },
  startButtonText: {
    ...theme?.typography.body.sans,
    fontWeight: '700',
    color: '#FFFFFF',
    fontSize: 16,
  },
  startHelper: {
    ...theme?.typography.caption.secondary,
    color: theme?.colors.text.secondary,
    marginBottom: theme?.spacing.sm,
  },
  countdownContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: theme?.spacing.lg
  },
  countdownCircle: {
    width: 160,
    height: 160,
    borderRadius: 80,
    borderWidth: 4,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: theme?.spacing.xl,
    backgroundColor: `${theme?.colors.background}E6`,
  },
  countdownText: {
    ...theme?.typography.heading.large,
    fontSize: 72,
    fontWeight: '700',
    textAlign: 'center',
    includeFontPadding: false,
    lineHeight: 80,
  },
  countdownSubtext: {
    ...theme?.typography.body.sans,
    color: theme?.colors.text.primary,
    fontSize: 18,
    marginBottom: theme?.spacing.md,
  },
  breatheText: { ...theme?.typography.caption.secondary, color: theme?.colors.text.secondary },
  activeContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: theme?.spacing.lg,
    paddingTop: theme?.spacing.xl * 1.5
  },
  breathCircleContainer: {
    width: 210,
    height: 210,
    borderRadius: 105,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  baseCircle: {
    width: '100%',
    height: '100%',
    borderRadius: 105,
  },
  timerLabelContainer: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  timerElapsed: {
    ...theme?.typography.heading.small,
    color: theme?.colors.text.primary,
    fontWeight: '700',
  },
  dismissText: {
    ...theme?.typography.caption.secondary,
    color: theme?.colors.text.secondary,
    marginTop: 2,
  },
  smartPickWrapper: {
    width: '100%',
    marginBottom: theme?.spacing.lg,
  },
  timerTotal: {
    ...theme?.typography.caption.secondary,
    color: theme?.colors.text.secondary,
    marginTop: 2,
  },
  breathGradient: {
    width: '100%',
    height: '100%',
    borderRadius: 1000,
    overflow: 'hidden',
    position: 'absolute',
    borderWidth: 1,
    borderColor: `${currentVirtue?.color_code || theme?.colors.primary}40`,
  },
  breatheInstructionContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10, // Ensure this is on top
  },
  breatheInstructionBackground: {
    // backgroundColor: `${theme.colors.background}CC`, // More opaque background
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: `${currentVirtue?.color_code || theme?.colors.primary}40`,
    ...Platform.select({
      ios: {
        shadowColor: theme.colors.text.primary,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 3
      },
      android: { elevation: 2 },
    }),
  },
  breatheInstruction: {
    ...theme?.typography.body.sans,
    color: currentVirtue?.color_code || theme?.colors.primary,
    fontSize: 17,
    fontWeight: '700',
    minWidth: 170,
    textAlign: 'center',
    textShadowColor: 'rgba(255, 255, 255, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 2,
  },
  declarationContainer: {
    width: '100%',
    marginTop: theme?.spacing.lg,
    padding: theme?.spacing.md,
    borderRadius: theme?.borderRadius.md,
    backgroundColor: `${theme?.colors.surface}E6`,
    borderWidth: 1,
    borderColor: `${theme?.colors.border}80`,
    gap: theme?.spacing.sm,
  },
  declarationLabel: {
    ...theme?.typography.caption.secondary,
    color: theme?.colors.text.secondary,
    textTransform: 'uppercase',
    letterSpacing: 1,
    fontWeight: '600',
  },
  declarationText: {
    ...theme?.typography.body.sans,
    color: theme?.colors.text.primary,
    lineHeight: 22,
  },
  controlsRow: {
    flexDirection: 'row',
    width: '100%',
    gap: theme?.spacing.sm,
    marginTop: theme?.spacing.md,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  controlBtn: {
    flex: 1,
    paddingVertical: theme?.spacing.md,
    borderRadius: theme?.borderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme?.colors.border,
    backgroundColor: theme?.colors.surface,
  },
  pauseBtn: {
    backgroundColor: `${theme?.colors.surface}E6`,
    borderColor: `${theme?.colors.border}AA`,
  },
  endBtn: {
    backgroundColor: `${theme?.colors.primary}12`,
    borderColor: `${theme?.colors.primary}66`,
  },
  controlBtnText: {
    ...theme?.typography.body.sans,
    fontWeight: '700',
  },
  pauseBtnText: {
    color: theme?.colors.text.primary,
  },
  endBtnText: {
    color: currentVirtue?.color_code || theme?.colors.primary,
  },
  jpGuideContainer: {
    alignItems: 'center',
    gap: theme?.spacing.xs,
    marginTop: theme?.spacing.sm,
  },
  jpPhrase: {
    ...theme?.typography.caption.secondary,
    color: theme?.colors.text.secondary,
  },
  jpPhraseActive: {
    color: currentVirtue?.color_code || theme?.colors.primary,
    fontWeight: '700',
  },
  nowPlayingCard: {
    marginTop: theme?.spacing.md,
    padding: theme?.spacing.md,
    borderRadius: theme?.borderRadius.md,
    borderWidth: 1,
    borderColor: theme?.colors.border,
    backgroundColor: theme?.colors.surface,
    alignItems: 'center',
  },
  nowPlayingTitle: {
    ...theme?.typography.caption.secondary,
    color: theme?.colors.text.secondary,
    marginBottom: 4,
  },
  nowPlayingText: {
    ...theme?.typography.body.sans,
    color: theme?.colors.text.primary,
    fontWeight: '700',
    fontSize: 16,
  },
  idleContainer: { padding: theme.spacing.lg },
  idleCard: {
    padding: theme.spacing.lg,
    borderRadius: theme.borderRadius.lg,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginBottom: theme.spacing.lg,
    alignItems: 'center',
  },
  idleTitle: {
    ...theme.typography.heading.small,
    color: theme.colors.text.primary,
    fontWeight: '700',
  },
  idleSubtitle: {
    ...theme.typography.caption.secondary,
    color: theme.colors.text.secondary,
    marginTop: 4,
  },
  idleRow: { flexDirection: 'row', gap: theme.spacing.sm },
  idleBtn: {
    flex: 1,
    paddingVertical: theme.spacing.md,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1.5,
    borderColor: theme.colors.border,
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
  },
  idleBtnPrimary: { backgroundColor: theme.colors.primary, borderColor: theme.colors.primary },
  idleBtnText: { ...theme.typography.body.sans, color: theme.colors.text.primary, fontWeight: '600' },
  idleBtnTextPrimary: { color: '#FFF' },
  completeContainer: { flex: 1, alignItems: 'center', justifyContent: 'space-between', padding: theme.spacing.lg },
  completeBanner: { width: '100%', alignItems: 'center', marginTop: theme.spacing.xl },
  completeTitle: {
    ...theme.typography.heading.medium,
    color: theme.colors.text.primary,
    marginVertical: theme.spacing.md,
  },
  completeSubtitle: {
    ...theme.typography.body.sans,
    color: theme.colors.text.secondary,
    textAlign: 'center',
  },
  bellButton: { alignItems: 'center' },
  bellIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: theme.spacing.md,
  },
  bellText: {
    ...theme.typography.caption.primary,
    color: theme.colors.text.primary,
    fontWeight: '600',
  },
  finishButton: {
    marginTop: theme.spacing.xl,
    paddingVertical: theme.spacing.md,
    paddingHorizontal: theme.spacing.xl,
    borderRadius: theme.borderRadius.full,
    backgroundColor: theme.colors.primary,
    alignSelf: 'center',
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.15, shadowRadius: 8 },
      android: { elevation: 4 },
    }),
  },
  finishButtonText: {
    ...theme.typography.body.sans,
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 16,
  },
  challengeSummaryContainer: {
    width: '100%',
    marginBottom: theme.spacing.xl,
  },
  challengeSummaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.spacing.sm,
    marginBottom: theme.spacing.xs,
  },
  challengeSummaryTitle: {
    ...theme.typography.caption.secondary,
    color: theme.colors.text.secondary,
  },
  challengeToggleLabel: {
    ...theme.typography.caption.secondary,
    color: theme.colors.text.secondary,
  },
  challengeSummaryCard: {
    padding: theme.spacing.lg,
    borderRadius: theme.borderRadius.lg,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
    overflow: 'hidden',
  },
  challengeSummaryText: {
    ...theme.typography.body.sans,
    color: theme.colors.text.primary,
    fontWeight: '600',
    marginBottom: theme.spacing.sm,
  },
  challengeDuration: { ...theme.typography.caption.secondary, color: theme.colors.text.secondary },
  placeholderText: {
    ...theme?.typography.body.sans,
    color: theme?.colors.text.secondary,
    textAlign: 'center',
    paddingVertical: theme?.spacing.xl,
  },
  selectedVirtueCollapsed: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: theme?.spacing.md,
    borderRadius: theme?.borderRadius.md,
    borderWidth: 1.5,
    backgroundColor: `${currentVirtue?.color_code || theme?.colors.primary}08`,
    marginBottom: theme?.spacing.md,
  },
  selectedVirtueContent: { flexDirection: 'row', alignItems: 'center', gap: theme?.spacing.md },
  changeVirtueButton: {
    paddingVertical: theme?.spacing.xs,
    paddingHorizontal: theme?.spacing.sm,
    borderRadius: theme?.borderRadius.sm,
    backgroundColor: theme?.colors.surface,
    borderWidth: 1,
    borderColor: theme?.colors.border,
  },
  changeVirtueText: {
    ...theme?.typography.caption.secondary,
    color: theme?.colors.text.secondary,
    fontWeight: '500',
  },
  checkmarkContainer: {
    marginVertical: theme.spacing.lg,
    alignItems: 'center',
  },
  checkCircle: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#4CAF50',
    alignItems: 'center',
    justifyContent: 'center',
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 4 },
      android: { elevation: 4 },
    }),
  },
  expandedChallengeInfo: {
    marginTop: theme.spacing.md,
    paddingTop: theme.spacing.md,
    borderTopWidth: 1,
    borderTopColor: `${theme.colors.border}80`,
  },
  expandedChallengeDescription: {
    ...theme.typography.body.sans,
    color: theme.colors.text.secondary,
    marginBottom: theme.spacing.md,
    lineHeight: 22,
  },
  virtueTagContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  virtueTag: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: theme.spacing.xs,
    paddingHorizontal: theme.spacing.sm,
    borderRadius: theme.borderRadius.md,
    marginRight: theme.spacing.xs,
  },
  virtueTagText: {
    ...theme.typography.caption.secondary,
    fontWeight: '600',
    marginLeft: 4,
  },
  retryButton: {
    backgroundColor: theme.colors.primary,
    paddingVertical: theme.spacing.md,
    paddingHorizontal: theme.spacing.lg,
    borderRadius: theme.borderRadius.full,
    marginTop: theme.spacing.md,
  },
  retryButtonText: {
    color: '#FFF',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: theme.spacing.lg,
  },
  modalCard: {
    width: '100%',
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.xl,
    padding: theme.spacing.lg,
    borderWidth: 1,
    borderColor: theme.colors.border,
    ...Platform.select({ ios: { shadowColor: '#000', shadowOpacity: 0.15, shadowRadius: 16, shadowOffset: { width: 0, height: 8 } }, android: { elevation: 8 } }),
  },
  modalTitle: {
    ...theme.typography.heading.medium,
    color: theme.colors.text.primary,
    textAlign: 'center',
    marginBottom: theme.spacing.sm,
  },
  modalText: {
    ...theme.typography.body.sans,
    color: theme.colors.text.secondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: theme.spacing.md,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  customModalCard: {
    width: '100%',
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.xl,
    padding: theme.spacing.lg,
    borderWidth: 1,
    borderColor: theme.colors.border,
    gap: theme.spacing.md,
  },
  customOptionsWrap: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: theme.spacing.sm,
  },
  customOptionButton: {
    flex: 1,
    paddingVertical: theme.spacing.md,
    borderRadius: theme.borderRadius.md,
    backgroundColor: `${theme.colors.primary}12`,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: `${theme.colors.primary}30`,
  },
  customOptionText: {
    ...theme.typography.body.sans,
    color: theme.colors.primary,
    fontWeight: '600',
  },
  customModalClose: {
    backgroundColor: `${theme.colors.primary}12`,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  modalBtn: {
    flex: 1,
    paddingVertical: theme.spacing.md,
    borderRadius: theme.borderRadius.full,
    alignItems: 'center',
  },
  modalBtnText: {
    ...theme.typography.body.sans,
    fontWeight: '700',
  },
  selectedChallengeCollapsed: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: theme?.spacing.md,
    borderRadius: theme?.borderRadius.md,
    borderWidth: 1.5,
    backgroundColor: `${currentVirtue?.color_code || theme?.colors.primary}08`,
    marginBottom: theme?.spacing.md,
  },
  selectedChallengeContent: { flex: 1, marginRight: theme?.spacing.md },
  challengeDescriptionCollapsed: {
    ...theme?.typography.caption.secondary,
    color: theme?.colors.text.secondary,
    marginTop: theme?.spacing.xs,
  },
  changeChallengeButton: {
    paddingVertical: theme?.spacing.xs,
    paddingHorizontal: theme?.spacing.sm,
    borderRadius: theme?.borderRadius.sm,
    backgroundColor: theme?.colors.surface,
    borderWidth: 1,
    borderColor: theme?.colors.border,
  },
  changeChallengeText: {
    ...theme?.typography.caption.secondary,
    color: theme?.colors.text.secondary,
    fontWeight: '500',
  },
  pausedOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  pausedBlur: {
    width: '85%',
    borderRadius: theme?.borderRadius.xl,
    overflow: 'hidden',
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.3, shadowRadius: 16 },
      android: { elevation: 8 },
    }),
  },
  pausedCard: {
    padding: theme?.spacing.xl,
    backgroundColor: theme?.colors.surface + 'F5',
    alignItems: 'center',
    gap: theme?.spacing.md,
  },
  pausedIconContainer: {
    marginBottom: theme?.spacing.sm,
  },
  pausedIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pausedIconText: {
    fontSize: 40,
    fontWeight: '300',
  },
  pausedTitle: {
    ...theme?.typography.heading.medium,
    color: theme?.colors.text.primary,
    fontWeight: '700',
    textAlign: 'center',
  },
  pausedSubtitle: {
    ...theme?.typography.body.sans,
    color: theme?.colors.text.secondary,
    textAlign: 'center',
    marginBottom: theme?.spacing.sm,
  },
  pausedActions: {
    width: '100%',
    gap: theme?.spacing.sm,
    marginTop: theme?.spacing.md,
  },
  pausedResumeButton: {
    paddingVertical: theme?.spacing.md + 2,
    paddingHorizontal: theme?.spacing.xl,
    borderRadius: theme?.borderRadius.full,
    alignItems: 'center',
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.2, shadowRadius: 8 },
      android: { elevation: 4 },
    }),
  },
  pausedResumeText: {
    ...theme?.typography.body.sans,
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 16,
  },
  pausedEndButton: {
    paddingVertical: theme?.spacing.md,
    paddingHorizontal: theme?.spacing.xl,
    borderRadius: theme?.borderRadius.full,
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderWidth: 1.5,
    borderColor: theme?.colors.border,
  },
  pausedEndText: {
    ...theme?.typography.body.sans,
    color: theme?.colors.text.secondary,
    fontWeight: '600',
    fontSize: 15,
  },
  offlineIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: theme?.spacing.xs,
    paddingHorizontal: theme?.spacing.sm,
    paddingVertical: theme?.spacing.xs,
    borderRadius: theme?.borderRadius.full,
    backgroundColor: `${theme?.colors.warning}12`,
    marginTop: theme?.spacing.xs,
    marginBottom: theme?.spacing.sm,
  },
  offlineIndicatorText: {
    ...theme?.typography.caption.secondary,
    color: theme?.colors.warning,
    fontWeight: '500',
    fontSize: 12,
  },
  offlineIndicatorCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme?.spacing.xs,
    paddingHorizontal: theme?.spacing.sm,
    paddingVertical: theme?.spacing.xs,
    borderRadius: theme?.borderRadius.full,
    backgroundColor: `${theme?.colors.warning}10`,
    alignSelf: 'center',
    marginBottom: theme?.spacing.sm,
  },
  offlineIndicatorCompactText: {
    ...theme?.typography.caption.secondary,
    color: theme?.colors.warning,
    fontWeight: '500',
    fontSize: 11,
  },
});
